upload-backend-release:
  stage: release
#  only:
#    changes:
#      - backend/**/*
#      - .gitlab-ci.yml
#     - devops/.*.yml
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -s settings.xml -Dversion.application=${VERSION} -DskipTests deploy