sonarqube-frontend-test:
  stage: test
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /testing/
  dependencies:
    - build-frontend-code-job
  image:
    name: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${KEY_SONAR}
      -Dsonar.host.url=${URL_SONAR}
      -Dsonar.login=${LOGIN_SONAR}
