sonarqube-frontend-test:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner \
      -Dsonar.projectKey=${KEY_SONAR} \
      -Dsonar.host.url=https://sonarqube.praktikum-services.ru \
      -Dsonar.login=${LOGIN_SONAR}
  needs:
    - build-frontend-code-job