sonarqube-frontend-test:
  stage: test
  dependencies:
    - build-frontend-code-job
  image:
    name: sonarsource/sonar-scanner-cli:latest
  needs:
    build-frontend-code-job
  script:
    - cd frontend
    - >
      sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${KEY_SONAR}
      -Dsonar.host.url=${URL_SONAR}
      -Dsonar.login=${LOGIN_SONAR}
