# !/bin/bash
echo -e "
"PSQL_HOST="$PSQL_HOST
"PSQL_PASS="$PSQL_PASS
"PSQL_PORT="$PSQL_PORT
"PSQL_BASE="$PSQL_BASE
"PSQL_USER="$PSQL_USER
"MONGO_HOST="$MONGO_HOST
"MONGO_PORT="$MONGO_PORT
"MONGO_USER="$MONGO_USER
"MONGO_PASS="$MONGO_PASS
"MONGO_BASE="$MONGO_BASE
" > /home/${DEV_USER}/sausage-store-backend.env