version: "3.3"

services:      # список сервисов
  backend:     # название сервиса
    # инструктируем docker-compose откуда брать образ
    image: gitlab.praktikum-services.ru:5050/d.ponizovskiy/sausage-store/sausage-backend:${BACKEND_VERSION}
    # бэкенд будет доступен для соседей по этому имени
    container_name: sausage-store-backend
    # переменные окружения, приложение читает и использует
    # их как параметры конфигурации
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true" 
      VIRTUAL_HOST: backend
    # в какой сети запускать контейнер
    networks:
      - sausage-store 



  backend-report:
    image: gitlab.praktikum-services.ru:5050/d.ponizovskiy/sausage-store/backend-report:${BACKEND_REPORT_VERSION}
    container_name: sausage-store-backend-report
    restart: unless-stopped
    environment:
      DB: ${SPRING_DATA_MONGODB_URI}
    networks:
      - sausage-store

  loadbalancer:
    image: gitlab.praktikum-services.ru:5050/d.ponizovskiy/sausage-store/sausage-frontend:${FRONTEND_VERSION}
    container_name: sausage-store-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: backend
    networks:
      - sausage-store


networks:
  sausage-store: